// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "S(MfVC1;uvCH7;NG#gj]":
            case "Lives":return img`
....................
....................
....................
....................
....................
....................
.......33...33......
......3333.3333.....
......333333333.....
......333333333.....
.......3333333......
........33333.......
.........333........
..........3.........
....................
....................
....................
....................
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
